"""master data tables

Revision ID: 22830db1b8a8
Revises: db784e9d1406
Create Date: 2026-09-05 11:18:07.559469

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22830db1b8a8'
down_revision = 'db784e9d1406'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_goods_receipts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('grn_number', sa.String(length=32), nullable=False),
    sa.Column('po_number', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity_ordered', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_goods_receipts'))
    )
    op.create_index(op.f('ix_master_goods_receipts_grn_number'), 'master_goods_receipts', ['grn_number'], unique=False)
    op.create_index(op.f('ix_master_goods_receipts_po_number'), 'master_goods_receipts', ['po_number'], unique=False)
    op.create_table('master_processed_invoices',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('internal_id', sa.String(length=32), nullable=False),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('vendor_id', sa.String(length=16), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('po_number', sa.String(length=32), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('processing_status', sa.String(length=32), nullable=True),
    sa.Column('processing_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_processed_invoices'))
    )
    op.create_index(op.f('ix_master_processed_invoices_internal_id'), 'master_processed_invoices', ['internal_id'], unique=True)
    op.create_index(op.f('ix_master_processed_invoices_invoice_number'), 'master_processed_invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_master_processed_invoices_vendor_id'), 'master_processed_invoices', ['vendor_id'], unique=False)
    op.create_table('master_vendors',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('vendor_id', sa.String(length=16), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('trading_name', sa.String(length=255), nullable=True),
    sa.Column('tax_pin', sa.String(length=64), nullable=True),
    sa.Column('vat_number', sa.String(length=64), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=True),
    sa.Column('bank_account_identifier', sa.String(length=128), nullable=True),
    sa.Column('vendor_category', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_vendors'))
    )
    op.create_index(op.f('ix_master_vendors_vendor_id'), 'master_vendors', ['vendor_id'], unique=True)
    op.create_table('master_purchase_orders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('po_number', sa.String(length=32), nullable=False),
    sa.Column('vendor_id', sa.String(length=16), nullable=False),
    sa.Column('po_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('delivery_status', sa.String(length=64), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['master_vendors.vendor_id'], name=op.f('fk_master_purchase_orders_vendor_id_master_vendors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_purchase_orders'))
    )
    op.create_index(op.f('ix_master_purchase_orders_po_number'), 'master_purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_master_purchase_orders_vendor_id'), 'master_purchase_orders', ['vendor_id'], unique=False)
    op.create_table('master_po_lines',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('po_id', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_treatment', sa.String(length=120), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('line_subtotal', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['master_purchase_orders.id'], name=op.f('fk_master_po_lines_po_id_master_purchase_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_po_lines'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_po_lines')
    op.drop_index(op.f('ix_master_purchase_orders_vendor_id'), table_name='master_purchase_orders')
    op.drop_index(op.f('ix_master_purchase_orders_po_number'), table_name='master_purchase_orders')
    op.drop_table('master_purchase_orders')
    op.drop_index(op.f('ix_master_vendors_vendor_id'), table_name='master_vendors')
    op.drop_table('master_vendors')
    op.drop_index(op.f('ix_master_processed_invoices_vendor_id'), table_name='master_processed_invoices')
    op.drop_index(op.f('ix_master_processed_invoices_invoice_number'), table_name='master_processed_invoices')
    op.drop_index(op.f('ix_master_processed_invoices_internal_id'), table_name='master_processed_invoices')
    op.drop_table('master_processed_invoices')
    op.drop_index(op.f('ix_master_goods_receipts_po_number'), table_name='master_goods_receipts')
    op.drop_index(op.f('ix_master_goods_receipts_grn_number'), table_name='master_goods_receipts')
    op.drop_table('master_goods_receipts')
    # ### end Alembic commands ###
