"""initial schema

Revision ID: db784e9d1406
Revises: 
Create Date: 2026-09-05 10:44:20.974915

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db784e9d1406'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('invoices',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('source_path', sa.String(length=1024), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=True),
    sa.Column('submitted_by_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], name=op.f('fk_invoices_submitted_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    op.create_index(op.f('ix_invoices_case_id'), 'invoices', ['case_id'], unique=False)
    op.create_index(op.f('ix_invoices_file_hash'), 'invoices', ['file_hash'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('invoice_id', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_jobs_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_invoice_id'), 'jobs', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('invoice_id', sa.String(length=32), nullable=True),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_audit_events_invoice_id_invoices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_audit_events_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_invoice_id'), 'audit_events', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_table('extractions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('invoice_id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('extraction_json', sa.JSON(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('ai_call_id', sa.String(length=64), nullable=True),
    sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_extractions_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_extractions_job_id_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extractions')),
    sa.UniqueConstraint('invoice_id', name=op.f('uq_extractions_invoice_id'))
    )
    op.create_table('validation_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('invoice_id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('report_id', sa.String(length=16), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=8), nullable=False),
    sa.Column('schema_version', sa.String(length=8), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('checks_json', sa.JSON(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_validation_runs_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_validation_runs_job_id_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_runs')),
    sa.UniqueConstraint('invoice_id', name=op.f('uq_validation_runs_invoice_id'))
    )
    op.create_index(op.f('ix_validation_runs_decision'), 'validation_runs', ['decision'], unique=False)
    op.create_index(op.f('ix_validation_runs_job_id'), 'validation_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_validation_runs_report_id'), 'validation_runs', ['report_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('record_id', sa.String(length=16), nullable=False),
    sa.Column('validation_run_id', sa.String(length=32), nullable=False),
    sa.Column('report_id', sa.String(length=16), nullable=False),
    sa.Column('invoice_number', sa.String(length=64), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('system_decision', sa.String(length=16), nullable=False),
    sa.Column('human_outcome', sa.String(length=24), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('decided_by_id', sa.String(length=32), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], name=op.f('fk_decisions_decided_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], name=op.f('fk_decisions_validation_run_id_validation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions')),
    sa.UniqueConstraint('record_id', name=op.f('uq_decisions_record_id')),
    sa.UniqueConstraint('validation_run_id', name=op.f('uq_decisions_validation_run_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decisions')
    op.drop_index(op.f('ix_validation_runs_report_id'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_job_id'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_decision'), table_name='validation_runs')
    op.drop_table('validation_runs')
    op.drop_table('extractions')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_invoice_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_invoice_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_file_hash'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_case_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
